### ISSUE TITLE
How can I add the Image icon to the default configuration

### ISSUE THREAD

**Issue by tcampbPPU** [edgarsn/nuxt-ckeditor-setup#1]
Hi, I found this repo while chasing down this very same issue as you, and I am wondering how am I able to add the Image icon to the default configuration.  

Thanks very much in advance :)

**Comment by edgarsn** [comment]
Hi!

This repo is experimental and not working sadly. CKeditor doesn't work with nuxt.js ssr right now.
I will update this repo as soon as it'll work.

You can check out this issue ckeditor/ckeditor5#6071 and make sure you add thumbs up.

For me the only solution was to create my own build with all plugins separately outside nuxt.js project. I described my solution [here](https://github.com/ckeditor/ckeditor5/issues/6071#issuecomment-580726752). That's the best you can get.

If you need more detalized description of how I implemented, let me now. 
Good luck :)

**Comment by tcampbPPU** [comment]
Hi again, I am trying to figure out how to link the script that is built from `webpack.config.js`  to my separate `nuxt` project. With the example, you have on your repo are you importing that webpack built script in your vue page?

**Comment by edgarsn** [comment]
After you've built your ckeditor.js file outside nuxt and moved/placed in your nuxt`s _static_ directory,
I link like a normal ES5 script.

**nuxt.config.js**
```javascript
export default {  
    head: {
        script: [
            {src: '/ckeditor.js'},
        ],
    }
}
```

.. or if your nuxt run's on subfolder not root (/), then `{src: '/subfolder/ckeditor.js'}`

You don't need that `build: { ...  }` part in this case, since it's already compiled outside nuxt.

If you still got some questions or suggestions, let me know.

**P.s.** As I mentioned, this repo code is not actual right now and you should ignore it anyway and not relate to our discussion in this case. I will update this repo as soon as ckeditor building in nuxt will be possible.

**Comment by tcampbPPU** [comment]
Thanks for clearing that up for me!!

**Comment by edgarsn** [comment]
No problem :ok_hand: 

I also updated readme file for others coming to this repo.
